window.petFood = [
    {
      catog: 'Dog',
      code: 'dog_performatrin',
      brand: 'PERFORMATRIN',
      description: 'ADULT CHICKEN & RICE FORMULA',
      weight: '12 LB',
      price: '$22.99',
    },
    {
      catog: 'Dog',
      code: 'dog_acana',
      brand: 'ACANA',
      description: 'ADULT SMALL BREED DOG FOOD',
      weight: '13 LB',
      price: '$46.99',
    },
    {
      catog: 'Dog',
      code: 'dog_barker',
      brand: 'BARKER',
      description: 'ADULT BEEF & VEGETABLE FLAVOR',
      weight: '12 LB',
      price: '$32.99',
    },
    {
      catog: 'Dog',
      code: 'dog_bluebufflo',
      brand: 'BLUE BUFFALO',
      description: 'BASICS LIMITED INGREDIENT FORMULA ADULT SALMON & POTATO RECIPE DOG FOOD',
      weight: '26 LB',
      price: '$51.99',
    },
    {
      catog: 'Cat',
      code: 'cat_diamondcare',
      brand: 'DIAMOND CARE',
      description: 'WEIGHT MANAGEMENT FORMULA',
      weight: '4 LB',
      price: '$27.99',
    },
    {
      catog: 'Cat',
      code: 'cat_wellness',
      brand: 'WELLNESS',
      description: 'COMPLETE HEALTH GRAIN FREE INDOOR HEALTH SALMON & HERRING MEAL RECIPE',
      weight: '4 LB',
      price: '$49.99',
    },
    {
      catog: 'Cat',
      code: 'cat_orijen',
      brand: 'ORIJEN',
      description: '6 FISH CAT FOOD',
      weight: '4 LB',
      price: '$34.99',
    },
    {
      catog: 'Cat',
      code: 'cat_merrick',
      brand: 'MERRICK',
      description: 'BACKCOUNTRY GAME BIRD RECIPE',
      weight: '3 LB',
      price: '$36.99',
    },
    {
      catog: 'Others',
      code: 'others_easypickens',
      brand: 'EASY PICKENS',
      description: 'BLACK OIL SUNFLOWER SEED',
      weight: '8.8 LB',
      price: '$15.49',
    },
    {
      catog: 'Others',
      code: 'others_armstrong',
      brand: 'ARMSTRONG',
      description: 'BLACK OIL SUNFLOWER SEED',
      weight: '3.63 KG',
      price: '$16.99',
    },
    {
      catog: 'Others',
      code: 'others_hagen',
      brand: 'HAGEN',
      description: 'GUINEA PIG PELLETS',
      weight: '2.26 KG',
      price: '$10.99',
    },
  ];
  